# Generated by Django 3.2.9 on 2021-11-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_data', '0003_calapiinadiutoriumcelebration_calapiinadiutoriumliturgicalday'),
        ('api', '0003_alter_cocktailingredient_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='feast',
            name='ext_calapi_inadiutorium_celebration',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feast', to='ext_data.calapiinadiutoriumcelebration'),
        ),
        migrations.AddField(
            model_name='feast',
            name='ext_calapi_inadiutorium_season',
            field=models.CharField(choices=[('ordinary', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter')], max_length=9, null=True),
        ),
    ]
