# Generated by Django 3.2.9 on 2021-12-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_data', '0003_calapiinadiutoriumcelebration_calapiinadiutoriumliturgicalday'),
        ('api', '0004_auto_20211117_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feast',
            options={'ordering': ['_date']},
        ),
        migrations.RenameField(
            model_name='feast',
            old_name='date',
            new_name='_date',
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='preparation',
            field=models.CharField(blank=True, choices=[('broken in half', 'Broken In Half'), ('chopped canned', 'Chopped Canned'), ('hollowed out', 'Hollowed Out'), ('thinly sliced', 'Thinly Sliced')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('broken in half', 'Broken In Half'), ('chopped canned', 'Chopped Canned'), ('cube', 'Cube'), ('cup', 'Cup'), ('dash', 'Dash'), ('drop', 'Drop'), ('hollowed out', 'Hollowed Out'), ('leaf', 'Leaf'), ('liter', 'Liter'), ('jigger', 'Jigger'), ('ounce', 'Ounce'), ('part', 'Part'), ('peel', 'Peel'), ('pint', 'Pint'), ('scoop', 'Scoop'), ('slice', 'Slice'), ('splash', 'Splash'), ('spiral', 'Spiral'), ('sprig', 'Sprig'), ('sprinkle', 'Sprinkle'), ('stalk', 'Stalk'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('thinly sliced', 'Thinly Sliced'), ('twist', 'Twist'), ('wedge', 'Wedge'), ('wheel', 'Wheel'), ('whole', 'Whole'), ('white', 'White'), ('yolk', 'Yolk'), ('zest', 'Zest')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feast',
            name='_date',
            field=models.DateField(blank=True, db_column='date', null=True),
        ),
        migrations.AlterField(
            model_name='feast',
            name='ext_calapi_inadiutorium_celebration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feast', to='ext_data.calapiinadiutoriumcelebration'),
        ),
        migrations.AlterField(
            model_name='feast',
            name='ext_calapi_inadiutorium_season',
            field=models.CharField(blank=True, choices=[('ordinary', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter')], max_length=9, null=True),
        ),
    ]
