# Generated by Django 3.2.9 on 2021-12-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211203_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktailingredient',
            options={'ordering': ('ingredient__name', 'amount', 'measurement'), 'verbose_name': 'Cocktail Ingredient', 'verbose_name_plural': 'Cocktail Ingredients'},
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='measurement',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('cube', 'Cube'), ('cup', 'Cup'), ('dash', 'Dash'), ('drop', 'Drop'), ('leaf', 'Leaf'), ('liter', 'Liter'), ('jigger', 'Jigger'), ('ounce', 'Ounce'), ('part', 'Part'), ('peel', 'Peel'), ('pint', 'Pint'), ('pound', 'Pound'), ('quart', 'Quart'), ('rind', 'Rind'), ('scoop', 'Scoop'), ('slice', 'Slice'), ('splash', 'Splash'), ('spiral', 'Spiral'), ('sprig', 'Sprig'), ('sprinkle', 'Sprinkle'), ('stalk', 'Stalk'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('to taste', 'To Taste'), ('twist', 'Twist'), ('wedge', 'Wedge'), ('wheel', 'Wheel'), ('whole', 'Whole'), ('white', 'White'), ('yolk', 'Yolk'), ('zest', 'Zest')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='preparation',
            field=models.CharField(blank=True, choices=[('broken in half', 'Broken In Half'), ('broken up', 'Broken Up'), ('chopped canned', 'Chopped Canned'), ('cut in pieces', 'Cut In Pieces'), ('hollowed out', 'Hollowed Out'), ('thinly sliced', 'Thinly Sliced'), ('sliced', 'Sliced'), ('juiced', 'Juiced'), ('grated', 'Grated'), ('ground', 'Ground')], default=None, max_length=255, null=True),
        ),
    ]
