# Generated by Django 3.2.6 on 2021-08-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('url', models.CharField(max_length=1855)),
                ('avg_price_per_liter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_per_liter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_50_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_100_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_200_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_375_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_473_18_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_750_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_5_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_75_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_50_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_100_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_200_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_375_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_473_18_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_750_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_5_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_75_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('controlled_beverage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.controlledbeverage')),
            ],
            options={
                'verbose_name': 'ABC Product',
                'verbose_name_plural': 'ABC Products',
            },
        ),
        migrations.CreateModel(
            name='ABCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default=None, max_length=250, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('pull_date', models.DateTimeField(verbose_name='date of price pull')),
                ('product_size', models.IntegerField(default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_data.abcproduct')),
            ],
        ),
    ]
