# Generated by Django 3.2.9 on 2021-11-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcproduct',
            name='avg_price_118_ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abcproduct',
            name='best_price_118_ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
