# Generated by Django 3.2.9 on 2022-06-29 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ext_data', '0003_calapiinadiutoriumcelebration_calapiinadiutoriumliturgicalday'),
    ]

    operations = [
        migrations.CreateModel(
            name='LidlProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ext_id', models.IntegerField(unique=True)),
                ('url', models.CharField(max_length=1855)),
            ],
            options={
                'verbose_name': 'Lidl Product',
                'verbose_name_plural': 'Lidl Products',
            },
        ),
        migrations.CreateModel(
            name='LidlProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pull_date', models.DateTimeField(verbose_name='date of price pull')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_data.lidlproduct')),
            ],
            options={
                'verbose_name': 'Lidl Product Price',
                'verbose_name_plural': 'Lidl Product Prices',
            },
        ),
    ]
